const ventanas = [
    "45 Funny Windows Error Messages.jpg",
    "AAAAAAAA.jpg",
    "boredom.jpg",
    "BuscadorWindowsXP.jpg",
    "Cat bug.jpg",
    "chooseYourAvatar.jpg",
    "descargar.jpg",
    "dsdS.jpg",
    "EfectoRaro.jpg",
    "erm wtfrack got the angel virus on my computer.jpg",
    "errorPorgramNoResponding.png",
    "fasdgfasd.jpg",
    "fucku.jpg",
    "GUIdebook _ Screenshots _ Windows 95.jpg",
    "Haha.jpg",
    "HelpVentana.jpg",
    "ig_ nis4white.jpg",
    "ILOVEYOU VIRUS.jpg",
    "Lilly___ Poor cat💔.jpg",
    "Loading.jpg",
    "LocalDiskError.png",
    "londyeliz 💌.jpg",
    "LookatmeEyes ventana.jpg",
    "loveError.png",
    "paginawierrdd.jpg",
    "PaintEninfinitosPaint.jpg",
    "paintEye.jpg",
    "pfp.jpg",
    "Pixel Eyes.jpg",
    "que.jpg",
    "ReproductorCementaryDrive.jpg",
    "ReproductorTourniquet.jpg",
    "reproductorWinAp.jpg",
    "Satellite Dreamcore_.jpg",
    "Solitaire and Minesweeper were created to trick you into PC learning.jpg",
    "Strange-Error.jpg",
    "TipaVentana.jpg",
    "trippy windows95 widget.jpg",
    "ventanaPaintConfondoCore.jpg",
    "virus infected.jpg",
    "VirusOjosGhostinurPC.jpg",
    "Vision.jpg",
    "WarningFish.jpg",
    "WarningFishes.jpg",
    "weird core.jpg",
    "weirdPage.jpg",
    "weird_web core made by me.jpg",
    "Windows 95.jpg",
    "windows error “fix”.jpg",
    "windows i love you error _D.jpg",
    "windowsUpdate.jpg",
    "windowsVIdeoReproducer.jpg",
    "windows_xp_funny_error_message.jpg",
    "windowxpPaintvacio.png",
    "xd.jpg",
    "xp-error-windows-xp.jpg",
    "xpfondo.jpg",
    "xxx.jpg",
    "YourComputerHatesU.jpg",
    "YourComputerSucks.jpg",
    "_.jpg",
    "¡¡ D R E A M C O R E (#5)!!.jpg",
    "ʚ ɞ.jpg",
    "🩷.jpg"
];